from typing import overload

class table:
    def __init__(self, z: int) -> None: ...
    def density(self) -> float: ...
    @overload
    def energy(cctbx, index: int) -> float: ...
    @overload
    def energy(cctbx) -> float: ...
    def lambda_at_angstrom(self, wavelength: float) -> float: ...
    def lambda_at_ev(self, energy: float) -> float: ...
    def lambda_at_kev(self, energy: float) -> float: ...
    def max_energy(self) -> float: ...
    def min_energy(self) -> float: ...
    def mu_at_angstrom(self, wavelength: float) -> float: ...
    def mu_at_ev(self, energy: float) -> float: ...
    def mu_at_kev(self, energy: float) -> float: ...
    @overload
    def mu_en_rho(cctbx, index: int) -> float: ...
    @overload
    def mu_en_rho(cctbx) -> float: ...
    def mu_en_rho_at_angstrom(self, wavelength: float) -> float: ...
    def mu_en_rho_at_ev(self, energy: float) -> float: ...
    def mu_en_rho_at_kev(self, energy: float) -> float: ...
    @overload
    def mu_rho(cctbx, index: int) -> float: ...
    @overload
    def mu_rho(cctbx) -> float: ...
    def mu_rho_at_angstrom(self, wavelength: float) -> float: ...
    def mu_rho_at_ev(self, energy: float) -> float: ...
    def mu_rho_at_kev(self, energy: float) -> float: ...
    def size(self) -> int: ...
