from __future__ import annotations

from typing import Any

class coordinate_frame_converter:
    CBF: str
    ROSSMANN: str
    MOSFLM: str
    def __init__(self, configuration_file: str) -> None: ...
    def get(self, parameter: str, convention: str = ...) -> Any: ...
    def get_c(self, parameter: str, convention: str = ...) -> Any: ...
    def move(self, vector, convention=...): ...
    def move_c(self, vector, convention=...): ...
    def get_u_b(self, convention=...): ...
    def get_unit_cell(self): ...
    def derive_beam_centre_pixels_fast_slow(self): ...
    def derive_detector_highest_resolution(self): ...
