from typing import Any, Optional, Tuple, Type

from .detectorbase import DetectorImageBase

class ADSCImage(DetectorImageBase):
    vendortype: str
    open_file: Any
    header: Any
    parameters: Any
    def __init__(self, filename: str) -> None: ...
    def readHeader(
        self, maxlength: int = ..., external_keys: Optional[Tuple[str, str, Type]] = ...
    ) -> None: ...
    def dataoffset(self): ...
    def integerdepth(self): ...
    def getEndian(self): ...
