from __future__ import annotations

def reverse_timestamp(timestamp): ...
def detector_format_version(address, timestamp): ...
def address_and_timestamp_from_detector_format_version(format_name): ...
