from typing import Any

from .detectorbase import DetectorImageBase

class DIPImage(DetectorImageBase):
    filename: Any
    vendortype: str
    filesize: Any
    deduce_size: int
    rawheader: Any
    parameters: Any
    def __init__(self, filename) -> None: ...
    def endian_swap_required(self): ...
    def fileLength(self): ...
    def floatformat(self): ...
    def getEndian(self): ...
    def getImageSize(self) -> None: ...
    def integerdepth(self): ...
    def intformat(self): ...
    def read(self) -> None: ...
    def readHeader(self) -> None: ...
