from typing import Any

from .detectorbase import DetectorImageBase

class MARImage(DetectorImageBase):
    vendortype: str
    endian: int
    depth: Any
    parameters: Any
    def __init__(self, filename) -> None: ...
    def isCompressed(self): ...
    def getEndian(self): ...
    def readHeader(self, offset: int = ...) -> None: ...
    def dataoffset(self): ...
    def integerdepth(self): ...
