from typing import Any

from .detectorbase import DetectorImageBase

class NullAdaptor:
    def size1(self): ...
    def size2(self): ...
    def overload(self): ...
    def pixel_size(self): ...
    def osc_start(self): ...
    def osc_range(self): ...
    def distance(self): ...
    def wavelength(self): ...
    def twotheta(self): ...
    def rawdata(self): ...

class MARIPImage(DetectorImageBase):
    adaptor: Any
    vendortype: str
    def __init__(self, filename) -> None: ...
    parameters: Any
    def readHeader(self) -> None: ...
    def beam_center_slow(self): ...
    def beam_center_fast(self): ...
    def fileLength(self): ...
    def getEndian(self): ...
    def read(self) -> None: ...
    def dataoffset(self): ...
    def integerdepth(self): ...
