from typing import Any

from .detectorbase import DetectorImageBase

class PilatusImage(DetectorImageBase):
    vendortype: str
    vendor_specific_null_value: int
    def __init__(self, filename) -> None: ...
    mandatory_keys: Any
    def fileLength(self) -> None: ...
    def getEndian(self) -> None: ...
    @staticmethod
    def is_bz2(filename): ...
    @staticmethod
    def is_gzip(filename): ...
    @staticmethod
    def open_file(filename, mode: str = ...): ...
    def endian_swap_required(self): ...
    adaptor: Any
    def read(self, algorithm: str = ...) -> None: ...
    header: Any
    headerlines: Any
    parameters: Any
    def readHeader(self, maxlength: int = ...) -> None: ...
