from __future__ import annotations

from typing import Any

from .detectorbase import DetectorImageBase
from .raxisbase import Raxis

class RAXISImage(DetectorImageBase, Raxis):
    vendortype: str
    parameters: Any
    def __init__(self, filename) -> None: ...
    def readHeader(self) -> None: ...  # type: ignore
    def generic_param_from_vendor_head(self) -> None: ...
    def dataoffset(self): ...
    def integerdepth(self): ...
    def getEndian(self): ...
    def read(self) -> None: ...
